/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.73
 * Generated at: 2023-06-01 05:47:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import java.sql.*;

public final class diary_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/dbconn.jsp", Long.valueOf(1685417444680L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1685405814933L));
    _jspx_dependants.put("jar:file:/D:/JSP-workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/cyworldrenew1/WEB-INF/lib/jstl-1.2.jar!/META-INF/sql.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/D:/JSP-workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/cyworldrenew1/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" \r\n");

	Connection conn = null;	

	try {
		String url = "jdbc:mysql://localhost:3306/cyworld";
		String user = "root";
		String password = "1111";

		Class.forName("com.mysql.jdbc.Driver");
		conn = DriverManager.getConnection(url, user, password);

	} catch (SQLException ex) {
		out.println("데이터베이스 연결이 실패되었습니다.<br>");
		out.println("SQLException: " + ex.getMessage());
	}
		

      out.write("\r\n");
      out.write("\r\n");

request.setCharacterEncoding("UTF-8");
String user_id = (String) session.getAttribute("sessionId");
PreparedStatement pstmt;
List<String> diary_contents = new ArrayList<>();
List<String> diary_date = new ArrayList<>();
try {
	String sql = "select * from diary where user_id=? order by diary_date DESC; ";
	pstmt = conn.prepareStatement(sql);
	pstmt.setString(1, user_id);
	ResultSet rs = pstmt.executeQuery();
	while (rs.next()) {
		String diary_contents1 = rs.getString("diary_content");
		String diary_date1 = rs.getString("diary_date");
		diary_contents.add(diary_contents1);
		diary_date.add(diary_date1);
	}
} catch (SQLException e) {
	e.printStackTrace();
}

String cyworld_url = "";
String user_mini_subject = "";
String user_miniroom_file = "";
try {
	String sql = "select * from user where user_id=?";
	String sql1 = "select * from profile where user_id=?";
	pstmt = conn.prepareStatement(sql);
	pstmt.setString(1, user_id);
	ResultSet rs = pstmt.executeQuery();
	while (rs.next()) {
		cyworld_url = rs.getString("cyworld_url");
	}
	pstmt = conn.prepareStatement(sql1);
	pstmt.setString(1, user_id); // user_id 값을 설정해야 합니다.
	ResultSet rs1 = pstmt.executeQuery();
	while (rs1.next()) {
		user_mini_subject = rs1.getString("user_mini_subject");
		user_miniroom_file = rs1.getString("user_miniroom_file");

	}

} catch (SQLException e) {
	e.printStackTrace();
}

String user_name = "";
String email = "";
String user_profile_photo = "";
String user_hello_word = "";
try {
	String sql = "select * from user where user_id=?";
	String sql1 = "select * from profile where user_id=?";
	pstmt = conn.prepareStatement(sql);
	pstmt.setString(1, user_id);
	ResultSet rs = pstmt.executeQuery();
	while (rs.next()) {
		user_name = rs.getString("user_name");
		email = rs.getString("email");
	}
	pstmt = conn.prepareStatement(sql1);
	pstmt.setString(1, user_id); // user_id 값을 설정해야 합니다.
	ResultSet rs1 = pstmt.executeQuery();
	while (rs1.next()) {
		user_profile_photo = rs1.getString("user_profile_photo");
		user_hello_word = rs1.getString("user_hello_word");
	}
} catch (SQLException e) {
	e.printStackTrace();
}

try {

	String sql1 = "select * from profile where user_id=?";

	pstmt = conn.prepareStatement(sql1);
	pstmt.setString(1, user_id); // user_id 값을 설정해야 합니다.
	ResultSet rs1 = pstmt.executeQuery();
	while (rs1.next()) {
		user_miniroom_file = rs1.getString("user_miniroom_file");

	}

} catch (SQLException e) {
	e.printStackTrace();
}

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"EUC-KR\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style>\r\n");
      out.write("* {\r\n");
      out.write("	margin: 0 auto;\r\n");
      out.write("	box-sizing: border-box;\r\n");
      out.write("	list-style: none;\r\n");
      out.write("	border: 1px solid black;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#mini_container {\r\n");
      out.write("	width: 1400px;\r\n");
      out.write("	height: 850px;\r\n");
      out.write("	border: 1px solid;\r\n");
      out.write("	position: relative;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#mini_background1 {\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	height: 100%;\r\n");
      out.write("	background: url(background/background.png) no-repeat center;\r\n");
      out.write("	background-size: cover;\r\n");
      out.write("	position: absolute;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#mini_background2 {\r\n");
      out.write("	width: 95%;\r\n");
      out.write("	height: 95%;\r\n");
      out.write("	margin-top: 25px;\r\n");
      out.write("	border: 1px solid blue;\r\n");
      out.write("	background: url(background/outer.png) no-repeat center;\r\n");
      out.write("	background-size: cover;\r\n");
      out.write("	background-size: 100% 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#all_contentsdiv {\r\n");
      out.write("	width: 1300px;\r\n");
      out.write("	height: 800px;\r\n");
      out.write("	border: 1px solid red;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#left_contentsborderdiv {\r\n");
      out.write("	float: left;\r\n");
      out.write("	margin-top: 10px;\r\n");
      out.write("	width: 375px;\r\n");
      out.write("	border: 1px solid;\r\n");
      out.write("	height: 760px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#center_contentsdiv {\r\n");
      out.write("	box-sizing: border-box;\r\n");
      out.write("	margin-right: 0px;\r\n");
      out.write("	width: 700px;\r\n");
      out.write("	float: left;\r\n");
      out.write("	height: 760px;\r\n");
      out.write("	margin-top: 10px;\r\n");
      out.write("	border: 1px solid rgb(63, 231, 236);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#center_subject {\r\n");
      out.write("	margin-left: 23px;\r\n");
      out.write("	height: 6%;\r\n");
      out.write("	border: 1px solid;\r\n");
      out.write("	margin-top: 30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#left_contents_visitrate {\r\n");
      out.write("	margin-left: 45px;\r\n");
      out.write("	margin-top: 35px;\r\n");
      out.write("	margin-bottom: 0px;\r\n");
      out.write("	width: 80%;\r\n");
      out.write("	height: 5%;\r\n");
      out.write("	border: 1px solid rgb(6, 243, 38);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#right_contentsdiv_border {\r\n");
      out.write("	width: 180px;\r\n");
      out.write("	height: 760px;\r\n");
      out.write("	float: left;\r\n");
      out.write("	margin: 10px 0px;\r\n");
      out.write("	padding: 0px;\r\n");
      out.write("	position: relative;\r\n");
      out.write("	border: 1px solid brown;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#right_contentsdiv {\r\n");
      out.write("	width: 180px;\r\n");
      out.write("	height: 613px;\r\n");
      out.write("	float: left;\r\n");
      out.write("	border: 1px solid red;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#right_menu {\r\n");
      out.write("	width: 100px;\r\n");
      out.write("	height: 320px;\r\n");
      out.write("	border: 1px solid salmon;\r\n");
      out.write("	margin-top: 180px;\r\n");
      out.write("	float: left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#right_menu>div {\r\n");
      out.write("	padding: 5px;\r\n");
      out.write("	height: 40px;\r\n");
      out.write("	border-radius: 15px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#right_menu>div>a {\r\n");
      out.write("	margin-left: 5px;\r\n");
      out.write("	line-height: 30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#right_music {\r\n");
      out.write("	position: absolute;\r\n");
      out.write("	margin-left: 10px;\r\n");
      out.write("	top: 36px;\r\n");
      out.write("	width: 82%;\r\n");
      out.write("	height: 17%;\r\n");
      out.write("	border: 1px solid rebeccapurple;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#left_contentsdiv {\r\n");
      out.write("	margin-right: 0px;\r\n");
      out.write("	padding: 0px;\r\n");
      out.write("	width: 320px;\r\n");
      out.write("	margin-left: 35px;\r\n");
      out.write("	float: left;\r\n");
      out.write("	height: 680px;\r\n");
      out.write("	border: 1px solid rgb(219, 34, 34);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#left_contentsdiv1 {\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	height: 99%;\r\n");
      out.write("	border: 1px solid rgb(31, 250, 250);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#left_contents_userinfo {\r\n");
      out.write("	height: 100%;\r\n");
      out.write("	border-radius: 15px;\r\n");
      out.write("	padding: 5px;\r\n");
      out.write("	position: relative;\r\n");
      out.write("	border: 1px solid rgb(6, 243, 38);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#left_contents_userinfo>div {\r\n");
      out.write("	position: absolute;\r\n");
      out.write("	width: 94%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#user_profileimg {\r\n");
      out.write("	width: 100%;\r\n");
      out.write("	height: 30%;\r\n");
      out.write("	border: 1px solid rgb(6, 243, 38);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#today_feeling {\r\n");
      out.write("	height: 5%;\r\n");
      out.write("	top: 32%;\r\n");
      out.write("	border: 1px solid pink;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#myself_introduce {\r\n");
      out.write("	height: 32%;\r\n");
      out.write("	border: 1px solid green;\r\n");
      out.write("	top: 38%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#user_name_email {\r\n");
      out.write("	height: 10%;\r\n");
      out.write("	top: 72%;\r\n");
      out.write("	border: 1px solid saddlebrown;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#cousin_select {\r\n");
      out.write("	height: 15%;\r\n");
      out.write("	top: 84%;\r\n");
      out.write("	border: 1px solid salmon;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#center_diarycontentsdiv1 {\r\n");
      out.write("	box-sizing: border-box;\r\n");
      out.write("	width: 650px;\r\n");
      out.write("	float: right;\r\n");
      out.write("	height: 645px;\r\n");
      out.write("	border: 1px solid rgb(70, 144, 241);\r\n");
      out.write("	margin-left: 13px;\r\n");
      out.write("	margin-top: 20px;\r\n");
      out.write("	word-wrap: break-word;\r\n");
      out.write("	overflow-y: scroll;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#center_diary_contents {\r\n");
      out.write("	width: 550px;\r\n");
      out.write("	height: 300px;\r\n");
      out.write("	border: 1px solid red;\r\n");
      out.write("	margin-left: 45px;\r\n");
      out.write("	margin-top: 130px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#center_diary_calendar {\r\n");
      out.write("	width: 550px;\r\n");
      out.write("	height: 120px;\r\n");
      out.write("	border: 1px solid rgb(233, 19, 161);\r\n");
      out.write("	margin-left: 45px;\r\n");
      out.write("	position: fixed;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("table {\r\n");
      out.write("	border-collapse: collapse;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("td {\r\n");
      out.write("	border: 1px solid black;\r\n");
      out.write("	line-height: 25px;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#calendar {\r\n");
      out.write("	width: 550px;\r\n");
      out.write("	height: 120px;\r\n");
      out.write("	border: 1px solid;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input {\r\n");
      out.write("	height: 20px;\r\n");
      out.write("	font-size: 15px;\r\n");
      out.write("	margin-bottom: 3px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#wrap {\r\n");
      out.write("	width: 550px;\r\n");
      out.write("	height: 120px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".center_diary_box {\r\n");
      out.write("	width: 550px;\r\n");
      out.write("	height: 300px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#center_contentsdiv1 {\r\n");
      out.write("	width: 685px;\r\n");
      out.write("	float: left;\r\n");
      out.write("	height: 685px;\r\n");
      out.write("	border: 1px solid rgb(109, 30, 255);\r\n");
      out.write("	margin-left: 13px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div id=\"mini_container\">\r\n");
      out.write("		<div id=\"mini_background1\">\r\n");
      out.write("			<div id=\"mini_background2\">\r\n");
      out.write("				<div id=\"all_contentsdiv\">\r\n");
      out.write("					<div id=\"left_contentsborderdiv\">\r\n");
      out.write("						<div id=\"left_contents_visitrate\">\r\n");
      out.write("							<label>Today 38 || Total 1000</label>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<div id=\"left_contentsdiv\">\r\n");
      out.write("							<div id=\"left_contentsdiv1\">\r\n");
      out.write("\r\n");
      out.write("								<div id=\"left_contents_userinfo\">\r\n");
      out.write("									<div id=\"user_profileimg\"\r\n");
      out.write("										style=\"background:url(userprofileimg/");
      out.print(user_profile_photo);
      out.write(") no-repeat center;background-size: contain;\">\r\n");
      out.write("\r\n");
      out.write("									</div>\r\n");
      out.write("									<div id=\"today_feeling\">오늘의 기분은 우울</div>\r\n");
      out.write("									<div id=\"myself_introduce\">");
      out.print(user_hello_word);
      out.write("</div>\r\n");
      out.write("									<div id=\"user_name_email\">\r\n");
      out.write("										");
      out.print(user_name);
      out.write("\r\n");
      out.write("										<br>");
      out.print(email);
      out.write("</div>\r\n");
      out.write("									<div id=\"cousin_select\"></div>\r\n");
      out.write("\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<div id=\"center_contentsdiv\">\r\n");
      out.write("						<div id=\"center_subject\">\r\n");
      out.write("							<p>");
      out.print(user_mini_subject);
      out.write("</p>\r\n");
      out.write("							<p>");
      out.print(cyworld_url);
      out.write("</p>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<div id=\"center_contentsdiv1\">\r\n");
      out.write("\r\n");
      out.write("							<div id=\"center_contents\">\r\n");
      out.write("\r\n");
      out.write("								<div id=\"center_diarycontentsdiv1\">\r\n");
      out.write("									<div id=\"center_diary_calendar\">\r\n");
      out.write("										<div id=\"calendar\">\r\n");
      out.write("											<div id=\"wrap\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("												<script>\r\n");
      out.write("													let date = new Date();\r\n");
      out.write("													let currentMonth = date\r\n");
      out.write("															.getMonth();\r\n");
      out.write("\r\n");
      out.write("													function prev() {\r\n");
      out.write("														date\r\n");
      out.write("																.setMonth(date\r\n");
      out.write("																		.getMonth() - 1);\r\n");
      out.write("														cal();\r\n");
      out.write("													}\r\n");
      out.write("\r\n");
      out.write("													function next() {\r\n");
      out.write("														date\r\n");
      out.write("																.setMonth(date\r\n");
      out.write("																		.getMonth() + 1);\r\n");
      out.write("														cal();\r\n");
      out.write("													}\r\n");
      out.write("													function cal() {\r\n");
      out.write("														let month = date\r\n");
      out.write("																.getMonth();\r\n");
      out.write("														let year = date\r\n");
      out.write("																.getFullYear();\r\n");
      out.write("\r\n");
      out.write("														let str = \"\";\r\n");
      out.write("\r\n");
      out.write("														str += \"<table>\";\r\n");
      out.write("\r\n");
      out.write("														str += \"<tr >\";\r\n");
      out.write("														str += \"<th colspan='21' style='width:550px;'>\"\r\n");
      out.write("																+ \"<input type='button' value='<<' onclick='prev()'>\"\r\n");
      out.write("																+ \"&nbsp;\"\r\n");
      out.write("																+ \"&nbsp;\"\r\n");
      out.write("																+ year\r\n");
      out.write("																+ \"년 \"\r\n");
      out.write("																+ (month + 1)\r\n");
      out.write("																+ \"월\"\r\n");
      out.write("																+ \"&nbsp;\"\r\n");
      out.write("																+ \"&nbsp;\"\r\n");
      out.write("																+ \"<input type='button' value='>>' onclick='next()'>\"\r\n");
      out.write("																+ \"</th>\";\r\n");
      out.write("														str += \"</tr>\";\r\n");
      out.write("\r\n");
      out.write("														str += \"<tr>\";\r\n");
      out.write("														str += \"<td>일</td>\";\r\n");
      out.write("														str += \"<td>월</td>\";\r\n");
      out.write("														str += \"<td>화</td>\";\r\n");
      out.write("														str += \"<td>수</td>\";\r\n");
      out.write("														str += \"<td>목</td>\";\r\n");
      out.write("														str += \"<td>금</td>\";\r\n");
      out.write("														str += \"<td>토</td>\";\r\n");
      out.write("														str += \"<td>일</td>\";\r\n");
      out.write("														str += \"<td>월</td>\";\r\n");
      out.write("														str += \"<td>화</td>\";\r\n");
      out.write("														str += \"<td>수</td>\";\r\n");
      out.write("														str += \"<td>목</td>\";\r\n");
      out.write("														str += \"<td>금</td>\";\r\n");
      out.write("														str += \"<td>토</td>\";\r\n");
      out.write("														str += \"<td>일</td>\";\r\n");
      out.write("														str += \"<td>월</td>\";\r\n");
      out.write("														str += \"<td>화</td>\";\r\n");
      out.write("														str += \"<td>수</td>\";\r\n");
      out.write("														str += \"<td>목</td>\";\r\n");
      out.write("														str += \"<td>금</td>\";\r\n");
      out.write("														str += \"<td>토</td>\";\r\n");
      out.write("														str += \"</tr>\";\r\n");
      out.write("\r\n");
      out.write("														// 이전 달의 마지막 날짜\r\n");
      out.write("														let prevMonthLastDate = new Date(\r\n");
      out.write("																year, month, 0)\r\n");
      out.write("																.getDate();\r\n");
      out.write("\r\n");
      out.write("														// 현재 달의 첫 번째 요일\r\n");
      out.write("														let firstDay = new Date(\r\n");
      out.write("																year, month, 1)\r\n");
      out.write("																.getDay();\r\n");
      out.write("\r\n");
      out.write("														// 현재 달의 마지막 날짜\r\n");
      out.write("														let lastDate = new Date(\r\n");
      out.write("																year,\r\n");
      out.write("																month + 1, 0)\r\n");
      out.write("																.getDate();\r\n");
      out.write("\r\n");
      out.write("														let cnt = 1;\r\n");
      out.write("\r\n");
      out.write("														for (let i = 0; i < 2; i++) {\r\n");
      out.write("															str += \"<tr >\";\r\n");
      out.write("\r\n");
      out.write("															for (let j = 0; j < 21; j++) {\r\n");
      out.write("																if (i === 0\r\n");
      out.write("																		&& j < firstDay) {\r\n");
      out.write("																	let prevDate = prevMonthLastDate\r\n");
      out.write("																			- firstDay\r\n");
      out.write("																			+ j\r\n");
      out.write("																			+ 1;\r\n");
      out.write("																	str += \"<td >\"\r\n");
      out.write("																			+ \" \"\r\n");
      out.write("																			+ \"</td>\";\r\n");
      out.write("																} else if (cnt <= lastDate) {\r\n");
      out.write("																	str += \"<td >\"\r\n");
      out.write("																			+ cnt\r\n");
      out.write("																			+ \"</td>\";\r\n");
      out.write("																	cnt++;\r\n");
      out.write("																} else {\r\n");
      out.write("																	str += \"<td >&nbsp;</td>\";\r\n");
      out.write("																}\r\n");
      out.write("															}\r\n");
      out.write("\r\n");
      out.write("															str += \"</tr>\";\r\n");
      out.write("														}\r\n");
      out.write("\r\n");
      out.write("														str += \"</table>\";\r\n");
      out.write("\r\n");
      out.write("														document\r\n");
      out.write("																.getElementById(\"wrap\").innerHTML = str;\r\n");
      out.write("													}\r\n");
      out.write("													cal();\r\n");
      out.write("												</script>\r\n");
      out.write("											</div>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div id=\"center_diary_contents\">\r\n");
      out.write("									<div id = \"center_diary_contents1\">\r\n");
      out.write("										<button onclick=\"showTextField()\">일기쓰기</button>\r\n");
      out.write("										<div id=\"center_diary_contents1\">\r\n");
      out.write("											");

											if (!diary_contents.isEmpty()) {
												for (int i = 0; i < diary_contents.size(); i++) {
											
      out.write("\r\n");
      out.write("											<div class=\"center_diary_box\">\r\n");
      out.write("												");
      out.print(diary_date.get(i));
      out.write("\r\n");
      out.write("												");
      out.print(diary_contents.get(i));
      out.write("\r\n");
      out.write("											</div>\r\n");
      out.write("											<br> <br>\r\n");
      out.write("											");

											}
											} else {
											
      out.write("\r\n");
      out.write("											<div class=\"center_diary_box\">일기를 열심히 쓰지 않았군요 일기를 씁시다</div>\r\n");
      out.write("											");

											}
											
      out.write("\r\n");
      out.write("										</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("										<div id=\"center_diary_contents2\" style=\"display:none;\">\r\n");
      out.write("											<form action=\"add_diary.jsp\" method=\"post\">\r\n");
      out.write("												<div id=\"date_select\" style=\"margin-left: 20px; float: left\">\r\n");
      out.write("													<select name=\"year\">\r\n");
      out.write("														<option value=\"2023\">2023</option>\r\n");
      out.write("														<option value=\"2022\">2022</option>\r\n");
      out.write("														<option value=\"2021\">2021</option>\r\n");
      out.write("														<option value=\"2020\">2020</option>\r\n");
      out.write("														<option value=\"2019\">2019</option>\r\n");
      out.write("\r\n");
      out.write("													</select >년 <select name=\"month\">\r\n");
      out.write("														");

														for (int i = 1; i < 13; i++) {
														
      out.write("\r\n");
      out.write("														\r\n");
      out.write("														");
if(i<10){
															
      out.write("<option value=\"0");
      out.print(i );
      out.write('"');
      out.write('>');
      out.write('0');
      out.print(i );
      out.write("</option>");
}
														
														else{
      out.write(" <option value=\"");
      out.print(i );
      out.write('"');
      out.write('>');
      out.print(i );
      out.write("</option> ");
}} 
      out.write("\r\n");
      out.write("													\r\n");
      out.write("															\r\n");
      out.write("															\r\n");
      out.write("													\r\n");
      out.write("														\r\n");
      out.write("														\r\n");
      out.write("													\r\n");
      out.write("													</select>월 <select name=\"day\">\r\n");
      out.write("														");

														for (int i = 1; i < 32; i++) {
														
      out.write("\r\n");
      out.write("														\r\n");
      out.write("														");
if(i<10){
															
      out.write("<option value=\"0");
      out.print(i );
      out.write('"');
      out.write('>');
      out.write('0');
      out.print(i );
      out.write("</option>");
}
														
														else{
      out.write(" <option value=\"");
      out.print(i );
      out.write('"');
      out.write('>');
      out.print(i );
      out.write("</option> ");
}} 
      out.write("\r\n");
      out.write("													\r\n");
      out.write("\r\n");
      out.write("													</select>일\r\n");
      out.write("												</div>\r\n");
      out.write("												<div id=\"button_div\"\r\n");
      out.write("													style=\"margin-right: 20px; float: right\">\r\n");
      out.write("													<button type=\"submit\" onclick=\"close_Textfield()\">저장</button>\r\n");
      out.write("													<button onclick=\"close_Textfield()\">취소</button>\r\n");
      out.write("												</div>\r\n");
      out.write("\r\n");
      out.write("												<textarea style=\"width: 100%; height: 90%;\" id=\"add_diary\"\r\n");
      out.write("													name=\"add_diary\">\r\n");
      out.write("								\r\n");
      out.write("								</textarea>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("											</form>\r\n");
      out.write("											\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function showTextField() {\r\n");
      out.write("    document.getElementById('center_diary_contents1').style.display = 'none';\r\n");
      out.write("    document.getElementById('center_diary_contents2').style.display = 'block';\r\n");
      out.write("}\r\n");
      out.write("    \r\n");
      out.write("    function     close_Textfield() {\r\n");
      out.write("        document.getElementById('center_diary_contents1').style.display = 'block';\r\n");
      out.write("        document.getElementById('center_diary_contents2').style.display = 'none';\r\n");
      out.write("    }\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("								</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div id=\"right_contentsdiv_border\">\r\n");
      out.write("						<div id=\"right_contentsdiv\">\r\n");
      out.write("							<div id=\"right_music\"></div>\r\n");
      out.write("							<div id=\"right_menu\">\r\n");
      out.write("								<div>\r\n");
      out.write("									<input type=\"radio\" id=\"home\" class=\"radioG\" name=\"radio1\"\r\n");
      out.write("										style=\"display: none;\"> <a href=\"index.jsp\"\r\n");
      out.write("										target=\"_parent\">홈</a>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div>\r\n");
      out.write("									<input type=\"radio\" id=\"profile\" class=\"radioG\" name=\"radio1\"\r\n");
      out.write("										style=\"display: none;\"> <a href=\"profile.jsp\"\r\n");
      out.write("										target=\"_parent\">프로필</a>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div>\r\n");
      out.write("									<input type=\"radio\" id=\"diary\" class=\"radioG\" name=\"radio1\"\r\n");
      out.write("										style=\"display: none;\"> <a href=\"diary.jsp\"\r\n");
      out.write("										target=\"_parent\">다이어리</a>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div>\r\n");
      out.write("									<input type=\"radio\" id=\"musicbox\" class=\"radioG\" name=\"radio1\"\r\n");
      out.write("										style=\"display: none;\"> <a href=\"index.html\"\r\n");
      out.write("										target=\"_parent\">주크박스</a>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div>\r\n");
      out.write("									<input type=\"radio\" id=\"photo\" class=\"radioG\" name=\"radio1\"\r\n");
      out.write("										style=\"display: none;\"> <a target=\"_parent\"\r\n");
      out.write("										href=\"photo.jsp\">사진첩</a>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div>\r\n");
      out.write("									<input type=\"radio\" id=\"board\" class=\"radioG\" name=\"radio1\"\r\n");
      out.write("										style=\"display: none;\"> <a target=\"_parent\"\r\n");
      out.write("										href=\"index.html\">게시판</a>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div>\r\n");
      out.write("									<input type=\"radio\" id=\"visitboard\" class=\"radioG\"\r\n");
      out.write("										name=\"radio1\" style=\"display: none;\"> <a\r\n");
      out.write("										target=\"_parent\" href=\"visit_board.jsp\">방명록</a>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div>\r\n");
      out.write("									<input type=\"radio\" id=\"settion\" class=\"radioG\" name=\"radio1\"\r\n");
      out.write("										style=\"display: none;\"> <a target=\"_parent\"\r\n");
      out.write("										href=\"index.html\">설정</a>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
