/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.73
 * Generated at: 2023-05-31 08:26:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import java.sql.*;

public final class profile_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/dbconn.jsp", Long.valueOf(1685417444680L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1685405814933L));
    _jspx_dependants.put("jar:file:/D:/JSP-workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/cyworldrenew1/WEB-INF/lib/jstl-1.2.jar!/META-INF/sql.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/D:/JSP-workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/cyworldrenew1/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" \r\n");

	Connection conn = null;	

	try {
		String url = "jdbc:mysql://localhost:3306/cyworld";
		String user = "root";
		String password = "1111";

		Class.forName("com.mysql.jdbc.Driver");
		conn = DriverManager.getConnection(url, user, password);

	} catch (SQLException ex) {
		out.println("데이터베이스 연결이 실패되었습니다.<br>");
		out.println("SQLException: " + ex.getMessage());
	}
		

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

request.setCharacterEncoding("UTF-8");
String user_id = (String) session.getAttribute("sessionId");
PreparedStatement pstmt;
String cyworld_url = null;
String user_mini_subject = null;
String user_miniroom_file = null;
String user_profile_photo = null;
String user_name = "";
String email = "";
String user_hello_word = "";
String user_profile_photo1 = "";
try {
	String sql = "select * from user where user_id=?";
	String sql1 = "select * from profile where user_id=?";
	pstmt = conn.prepareStatement(sql);
	pstmt.setString(1, user_id);
	ResultSet rs = pstmt.executeQuery();
	while (rs.next()) {
		cyworld_url = rs.getString("cyworld_url");
		user_name = rs.getString("user_name");
		email = rs.getString("email");
	}
	pstmt = conn.prepareStatement(sql1);
	pstmt.setString(1, user_id); // user_id 값을 설정해야 합니다.
	ResultSet rs1 = pstmt.executeQuery();
	while (rs1.next()) {
		user_mini_subject = rs1.getString("user_mini_subject");
		user_miniroom_file = rs1.getString("user_miniroom_file");
		user_profile_photo = rs1.getString("user_profile_photo");
		user_profile_photo1 = rs1.getString("user_profile_photo1");
		user_hello_word = rs1.getString("user_hello_word");
	}
} catch (SQLException e) {
	e.printStackTrace();
}

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link href=\"profile.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("	<div id=\"mini_container\">\r\n");
      out.write("		<div id=\"mini_background1\">\r\n");
      out.write("			<div id=\"mini_background2\">\r\n");
      out.write("				<div id=\"all_contentsdiv\">\r\n");
      out.write("					<div id=\"left_contentsborderdiv\">\r\n");
      out.write("						<div id=\"left_contents_visitrate\">\r\n");
      out.write("							<label>Today 38 || Total 1000</label>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div id=\"profile_contents_div\">\r\n");
      out.write("							<div id=\"profile_tag_subject\">\r\n");
      out.write("								profile\r\n");
      out.write("								<hr>\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("							<div id=\"profile_tag_div1\">\r\n");
      out.write("								<a href=\"\"> 자기소개</a>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div id=\"profile_tag_div2\">\r\n");
      out.write("								<a href=\"\">기본정보</a>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<div id=\"center_contentsdiv\">\r\n");
      out.write("						<div id=\"center_subject\">\r\n");
      out.write("							<p>");
      out.print(user_mini_subject);
      out.write("</p>\r\n");
      out.write("							<p>");
      out.print(cyworld_url);
      out.write("</p>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div id=\"center_contentsdiv1\">\r\n");
      out.write("							<div id=\"center_contents\">\r\n");
      out.write("								<div id=\"center_profile_img\">\r\n");
      out.write("									");

									if (user_profile_photo1 == null || user_profile_photo1.equals("")) {
									
      out.write("\r\n");
      out.write("									<img id=\"profileimg1\" src=\"userprofileimg/profile_default.jpg\">\r\n");
      out.write("									<label>개인 사진이 없네요. 우리 등록해봐요.</label>\r\n");
      out.write("									");

									} else {
									
      out.write("\r\n");
      out.write("									<img id=\"profileimg1\"\r\n");
      out.write("										src=\"userprofileimg/");
      out.print(user_profile_photo1);
      out.write("\">\r\n");
      out.write("									");

									}
									
      out.write("\r\n");
      out.write("\r\n");
      out.write("									<form id=\"formtag\" action=\"add_profileimg1.jsp\" method=\"post\"\r\n");
      out.write("										enctype=\"multipart/form-data\">\r\n");
      out.write("										<button id=\"edit_button\" type=\"button\" onclick=\"selectFile()\">Edit</button>\r\n");
      out.write("										<input type=\"submit\" id=\"edit_input\" value=\"edit\"\r\n");
      out.write("											style=\"display: none;\"> <input type=\"file\"\r\n");
      out.write("											id=\"fileinput\" name=\"fileinput\" style=\"display: none;\">\r\n");
      out.write("									</form>\r\n");
      out.write("\r\n");
      out.write("									<script>\r\n");
      out.write("											// 파일 선택 창 열기 및 자동 전환\r\n");
      out.write("											function selectFile() {\r\n");
      out.write("												document.getElementById(\r\n");
      out.write("														'fileinput').click();\r\n");
      out.write("											}\r\n");
      out.write("\r\n");
      out.write("											// 파일이 선택되었을 때 자동으로 페이지 전환\r\n");
      out.write("											document\r\n");
      out.write("													.getElementById('fileinput')\r\n");
      out.write("													.addEventListener(\r\n");
      out.write("															'change',\r\n");
      out.write("															function() {\r\n");
      out.write("																document\r\n");
      out.write("																		.getElementById(\r\n");
      out.write("																				'edit_input')\r\n");
      out.write("																		.click();\r\n");
      out.write("															});\r\n");
      out.write("										</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("								</div>\r\n");
      out.write("								<div id=\"center_profile_content\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("									<div id=\"profile_introduce_border1\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<button onclick=\"showTextArea()\">수정하기</button>\r\n");
      out.write("\r\n");
      out.write("										<div id=\"fileContent\"></div>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div id=\"profile_introduce_border2\" style=\"display:none;\">\r\n");
      out.write("										<form action=\"saveText.jsp\" method=\"post\">\r\n");
      out.write("											<button type=\"submit\" onclick=\"saveText();\">저장</button>\r\n");
      out.write("											<button  type=\"reset\" onclick=\"cancelEdit();\">취소</button>\r\n");
      out.write("											<textarea id=\"filecontent_textarea\" name=\"filecontent_textarea\"></textarea>\r\n");
      out.write("										</form>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("    window.addEventListener(\"load\", function() {\r\n");
      out.write("        var fileContentDiv = document.getElementById(\"fileContent\");\r\n");
      out.write("        var xhr = new XMLHttpRequest();\r\n");
      out.write("        xhr.open(\"GET\", \"");
      out.print(user_id);
      out.write(".txt\", true); // 표시할 파일의 경로와 파일명을 지정합니다.\r\n");
      out.write("        xhr.onreadystatechange = function() {\r\n");
      out.write("            if (xhr.readyState === 4 && xhr.status === 200) {\r\n");
      out.write("                fileContentDiv.textContent = xhr.responseText;\r\n");
      out.write("            }\r\n");
      out.write("        };\r\n");
      out.write("        xhr.send();\r\n");
      out.write("    });\r\n");
      out.write("    \r\n");
      out.write("    function showTextArea() {\r\n");
      out.write("        document.getElementById('profile_introduce_border1').style.display = 'none';\r\n");
      out.write("        document.getElementById('profile_introduce_border2').style.display = 'block';\r\n");
      out.write("        \r\n");
      out.write("        var fileContentDiv = document.getElementById(\"filecontent_textarea\");\r\n");
      out.write("        var xhr = new XMLHttpRequest();\r\n");
      out.write("        xhr.open(\"GET\", \"");
      out.print(user_id);
      out.write(".txt\", true); // 표시할 파일의 경로와 파일명을 지정합니다.\r\n");
      out.write("        xhr.onreadystatechange = function() {\r\n");
      out.write("            if (xhr.readyState === 4 && xhr.status === 200) {\r\n");
      out.write("                fileContentDiv.textContent = xhr.responseText;\r\n");
      out.write("            }\r\n");
      out.write("        };\r\n");
      out.write("        xhr.send();\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    function saveText() {\r\n");
      out.write("        var fileContent = document.getElementById(\"filecontent_textarea\").value;\r\n");
      out.write("        \r\n");
      out.write("        var xhr = new XMLHttpRequest();\r\n");
      out.write("        xhr.open(\"POST\", \"saveText.jsp\", true); // 데이터를 전송할 JSP 파일 경로를 지정합니다.\r\n");
      out.write("        xhr.setRequestHeader(\"Content-Type\", \"application/x-www-form-urlencoded\");\r\n");
      out.write("        xhr.onreadystatechange = function() {\r\n");
      out.write("            if (xhr.readyState === 4 && xhr.status === 200) {\r\n");
      out.write("                // 저장 완료 후 처리할 로직을 추가합니다.\r\n");
      out.write("            }\r\n");
      out.write("        };\r\n");
      out.write("        xhr.send(\"text=\" + encodeURIComponent(fileContent)); // 데이터를 전송합니다.\r\n");
      out.write("        \r\n");
      out.write("        document.getElementById('profile_introduce_border2').style.display = 'none';\r\n");
      out.write("        document.getElementById('profile_introduce_border1').style.display = 'block';\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    function cancelEdit() {\r\n");
      out.write("        document.getElementById('profile_introduce_border2').style.display = 'none';\r\n");
      out.write("        document.getElementById('profile_introduce_border1').style.display = 'block';\r\n");
      out.write("    }\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("		\r\n");
      out.write("				<div id=\"right_contentsdiv_border\">\r\n");
      out.write("					<div id=\"right_contentsdiv\">\r\n");
      out.write("						<div id=\"right_music\"></div>\r\n");
      out.write("						<div id=\"right_menu\">\r\n");
      out.write("							<div>\r\n");
      out.write("								<input type=\"radio\" id=\"home\" class=\"radioG\" name=\"radio1\"\r\n");
      out.write("									style=\"display: none;\"> <a href=\"index.jsp\"\r\n");
      out.write("									target=\"_parent\">홈</a>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div>\r\n");
      out.write("								<input type=\"radio\" id=\"profile\" class=\"radioG\" name=\"radio1\"\r\n");
      out.write("									style=\"display: none;\"> <a href=\"profile.jsp\"\r\n");
      out.write("									target=\"_parent\">프로필</a>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div>\r\n");
      out.write("								<input type=\"radio\" id=\"diary\" class=\"radioG\" name=\"radio1\"\r\n");
      out.write("									style=\"display: none;\"> <a href=\"diary.jsp\"\r\n");
      out.write("									target=\"_parent\">다이어리</a>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div>\r\n");
      out.write("								<input type=\"radio\" id=\"musicbox\" class=\"radioG\" name=\"radio1\"\r\n");
      out.write("									style=\"display: none;\"> <a href=\"index.html\"\r\n");
      out.write("									target=\"_parent\">주크박스</a>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div>\r\n");
      out.write("								<input type=\"radio\" id=\"photo\" class=\"radioG\" name=\"radio1\"\r\n");
      out.write("									style=\"display: none;\"> <a target=\"_parent\"\r\n");
      out.write("									href=\"photo.jsp\">사진첩</a>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div>\r\n");
      out.write("								<input type=\"radio\" id=\"board\" class=\"radioG\" name=\"radio1\"\r\n");
      out.write("									style=\"display: none;\"> <a target=\"_parent\"\r\n");
      out.write("									href=\"index.html\">게시판</a>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div>\r\n");
      out.write("								<input type=\"radio\" id=\"visitboard\" class=\"radioG\" name=\"radio1\"\r\n");
      out.write("									style=\"display: none;\"> <a target=\"_parent\"\r\n");
      out.write("									href=\"visit_board.jsp\">방명록</a>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div>\r\n");
      out.write("								<input type=\"radio\" id=\"settion\" class=\"radioG\" name=\"radio1\"\r\n");
      out.write("									style=\"display: none;\"> <a target=\"_parent\"\r\n");
      out.write("									href=\"index.html\">설정</a>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>	</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
